### ISSUE TITLE
nodejs-legacy only works for distro-supported node.js

### ISSUE THREAD

**Issue by rusher81572** [rusher81572/picluster#21]
```
nodejs-legacy : Depends: nodejs (>= 0.6.19~dfsg1-3~) but it is not going to be installed
```

When trying to upgrade to a more recent version of node.js, I can not install nodejs-legacy which results in the node command not being found in the Web Console

```
curl -sL https://deb.nodesource.cox -o nodesource_setup.sh;
bash nodesource_setup.sh
apt-get install nodejs -y
```

@aidanharris, thoughts on a proper workaround?

**Comment by aidanharris** [comment]
@rusher81572 You don't need the nodejs-legacy package if you install from nodesource since they use use `node` like upstream and everyone else so everything "just works". You should remove nodejs-legacy before installing / upgrading nodejs.

If you want an idea of what I did see [here](https://github.com/aidanharris/picluster/wiki/Installation-on-Raspbian). I'd add it to the wiki but don't have write access 😉

**Comment by aidanharris** [comment]
@rusher81572 If you're still having issues can you confirm that this [Dockerfile](https://gist.github.com/b2c8021c1b2eb881d606d48a8fc19f09) will build for you (it does for me). I think somehow your environment is broken?

**Comment by rusher81572** [comment]
I removed node-legacy and I am up and running. I think we should recommend node.js v8 in the readme that should address this.
